In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/manoj9april/imbd-sentiment-classification-dataset/data/train.json
/kaggle/input/datasets/manoj9april/imbd-sentiment-classification-dataset/data/test.json
/kaggle/input/datasets/keerthisuresh12/imbd-sentimental/IMDB Dataset.csv

In [2]:
df = df = pd.read_csv("/kaggle/input/datasets/keerthisuresh12/imbd-sentimental/IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.shape
df.columns
print(df['sentiment'].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [5]:

print(df['review'].iloc[0])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [6]:
df['review'].str.len().describe()
#number of characters -

count    50000.000000
mean      1309.431020
std        989.728014
min         32.000000
25%        699.000000
50%        970.000000
75%       1590.250000
max      13704.000000
Name: review, dtype: float64

In [7]:
df['review'].str.split().str.len().describe()
#split() = number of words  - how long the reviews are in terms of words

count    50000.000000
mean       231.156940
std        171.343997
min          4.000000
25%        126.000000
50%        173.000000
75%        280.000000
max       2470.000000
Name: review, dtype: float64

In [8]:
for max_len in [100 , 150 , 200 , 250 , 300 , 400 , 500 , 600]:
    percentage = (df['review'].str.split().str.len() <= max_len).mean() * 100
    print(max_len , f"{percentage:2f}%")

100 12.242000%
150 39.910000%
200 59.140000%
250 70.416000%
300 77.708000%
400 87.032000%
500 92.194000%
600 95.252000%

In [9]:
#1 step 
#buil in regular expression module 
import re 
text = df['review'].iloc[0]
clean_text = re.sub(r'<[^>]+>' ,'' , text) 
#sub = find this pattern and substitute with something else - html with space 
print("before:")
print(text)
print("\n AFter:")
print(clean_text)

before:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

 AFter:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [10]:
def clean_text(text):
    text = re.sub(r'<[^>]+>',' ', text)
    text = re.sub(r'\s+' , ' ', text)
    return text.strip().lower()

In [11]:
#apply for whole dataset 
df['clean_review'] = df['review'].apply(clean_text)
print(df[['review' , 'clean_review']].head())

                                              review  \
0  One of the other reviewers has mentioned that ...
1  A wonderful little production. <br /><br />The...
2  I thought this was a wonderful way to spend ti...
3  Basically there's a family where a little boy ...
4  Petter Mattei's "Love in the Time of Money" is...

                                        clean_review
0  one of the other reviewers has mentioned that ...
1  a wonderful little production. the filming tec...
2  i thought this was a wonderful way to spend ti...
3  basically there's a family where a little boy ...
4  petter mattei's "love in the time of money" is...

In [12]:
print(df['clean_review'].iloc[0])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me. the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word. it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away. i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [13]:
#tokenization 
tokens = df['clean_review'].iloc[0].split()
print(tokens[:20])
print("number of tokens:" , len(tokens))

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', '1', 'oz', 'episode', "you'll", 'be', 'hooked.', 'they', 'are', 'right,']
number of tokens: 304

In [14]:
from sklearn.model_selection import train_test_split
train_df , test_df = train_test_split(df , test_size =0.2 , random_state = 42 , stratify = df['sentiment'])
print(train_df.shape)
print(test_df.shape)
print(train_df['sentiment'].value_counts())
print(test_df['sentiment'].value_counts())

(40000, 3)
(10000, 3)
sentiment
positive    20000
negative    20000
Name: count, dtype: int64
sentiment
negative    5000
positive    5000
Name: count, dtype: int64

A vocabulary is simply a mapping: word → integer ID
Why numbers? Because our nn.Embedding layer expects integer IDs, not strings.


PAD - reviews are of different length -  batch needs tensors with same shape 
<unk> = 1 
<pad> = 0 
known words =start from2

In [15]:
train_df

,review,sentiment,clean_review
47808,I caught this little gem totally by accident b...,positive,i caught this little gem totally by accident b...
20154,I can't believe that I let myself into this mo...,negative,i can't believe that i let myself into this mo...
43069,*spoiler alert!* it just gets to me the nerve ...,negative,*spoiler alert!* it just gets to me the nerve ...
19413,If there's one thing I've learnt from watching...,negative,if there's one thing i've learnt from watching...
13673,"I remember when this was in theaters, reviews ...",negative,"i remember when this was in theaters, reviews ..."
...,...,...,...
31092,It's the 1920s. And a man named Walt Disney wa...,positive,it's the 1920s. and a man named walt disney wa...
22917,"The first (and only) time I saw ""Shades"" was d...",negative,"the first (and only) time i saw ""shades"" was d..."
47481,This was such a waste of time. Danger: If you ...,negative,this was such a waste of time. danger: if you ...
35597,this is by far the most pathetic movie Indian ...,negative,this is by far the most pathetic movie indian ...
27491,This movie forever left an impression on me. I...,negative,this movie forever left an impression on me. i...

In [16]:
test_df

,review,sentiment,clean_review
18870,"Yes, MTV there really is a way to market Daria...",negative,"yes, mtv there really is a way to market daria..."
39791,The story of the bride fair is an amusing and ...,negative,the story of the bride fair is an amusing and ...
30381,"A team varied between Scully and Mulder, two o...",positive,"a team varied between scully and mulder, two o..."
42294,This was a popular movie probably because of t...,negative,this was a popular movie probably because of t...
33480,This movie made me so angry!! Here I am thinki...,negative,this movie made me so angry!! here i am thinki...
...,...,...,...
3634,SILVER CITY (2+ outta 5 stars) As a huge fan o...,negative,silver city (2+ outta 5 stars) as a huge fan o...
47910,Moscow Zero stole my money and I want it back!...,negative,moscow zero stole my money and i want it back!...
16086,This is the only film I've seen that is made b...,negative,this is the only film i've seen that is made b...
48294,"This is a story about Shin-ae, who moves to Mi...",positive,"this is a story about shin-ae, who moves to mi..."
4478,Leon Errol handles his double role of Uncle Ma...,negative,leon errol handles his double role of uncle ma...

In [17]:
#splitting the words and ciunting the appearances of each word in the whole 40k dataset 
from collections import Counter 
word_counts = Counter()
for review in train_df['clean_review']:
    words = review.split()
    word_counts.update(words)
print(word_counts.most_common(20))

[('the', 523625), ('a', 254816), ('and', 252286), ('of', 229828), ('to', 212541), ('is', 163863), ('in', 145664), ('i', 119932), ('this', 114764), ('it', 105524), ('that', 104546), ('was', 74989), ('as', 71810), ('for', 68518), ('with', 68053), ('but', 63317), ('on', 50649), ('movie', 49250), ('not', 45823), ('are', 45724)]

In [18]:
print("unique words:" , len(word_counts))

unique words: 318011

In [19]:
# min_freq = 2 
# (keeping the words only if it appears atleast twice )

In [20]:
for min_freq in [1 , 2 ,3 ,5 , 10]:
    vocab_size = sum(
        1 for count in word_counts.values()
        if count >= min_freq
        
    )
    print(f"min_freq = {min_freq}:{vocab_size}words")

min_freq = 1:318011words
min_freq = 2:127594words
min_freq = 3:89080words
min_freq = 5:59845words
min_freq = 10:36173words

In [21]:
#we are choosing 5 as threshold frequency so the total words = 59845 with pad and unk +2 =59847

In [22]:
min_frequency= 5

In [23]:
vocab = {
    "<PAD>" : 0,
    "<UNK>" : 1
}

In [24]:
#now add the words that are min = 5 frequency 
for word , count in word_counts.items():
    if count >= min_frequency:
        vocab[word] = len(vocab)
print("vocabulary size:" , len(vocab))
print(list(vocab.items())[:20])

vocabulary size: 59847
[('<PAD>', 0), ('<UNK>', 1), ('i', 2), ('caught', 3), ('this', 4), ('little', 5), ('gem', 6), ('totally', 7), ('by', 8), ('accident', 9), ('back', 10), ('in', 11), ('1980', 12), ('or', 13), ('was', 14), ('at', 15), ('a', 16), ('revival', 17), ('theatre', 18), ('to', 19)]

In [25]:
#converting the words into ids 
def encode_review(review):
    tokens = review.split()
    ids = []
    for token in tokens:
        ids.append(vocab.get(token , vocab["<UNK>"]))
    return ids

In [26]:
#testing it on one review
sample = train_df['clean_review'].iloc[0]
encoded = encode_review(sample)
print(sample.split()[:20])
print(encoded[:20])

['i', 'caught', 'this', 'little', 'gem', 'totally', 'by', 'accident', 'back', 'in', '1980', 'or', "'81.", 'i', 'was', 'at', 'a', 'revival', 'theatre', 'to']
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2, 14, 15, 16, 17, 18, 19]

In [27]:
print(len(vocab))
print(max(vocab.values()))

59847
59846

trunacating and padding - becuase our revuews have different umber of tokens 
but pytorch needs rectangular tensor [batch_size , sequence length]
hence max_len = 500 if a review has more than 500 tokens truncate it 
if review has fewer tokens pad it

In [28]:
def encode_and_pad(review , max_len=500):
    ids = encode_review(review)
    if len(ids) > max_len:
        ids = ids[:max_len]
    else:
        ids = ids +[vocab["<PAD>"]] * (max_len - len(ids))
    return ids

In [29]:
encoded = encode_and_pad(train_df['clean_review'].iloc[0])
print(len(encoded))
print(encoded[:20])
print(encoded[-20:])

500
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 2, 14, 15, 16, 17, 18, 19]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [30]:
# we need to do all this for 40k training set so that is avilable for pytirch 
# dataset - dataset[0]

# → ([2, 3, 4, 5, ..., 0], 1) - it gives reviews ids with its label 
# class IMDBDataset(Dataset):

In [31]:
#converting sentiment positive nad negative to numbers -0 ,1
train_df['label'] = train_df['sentiment'].map({
    'negative' : 0 , 
    'positive' : 1
})
test_df['label'] = test_df['sentiment'].map({
    'negative' : 0,
    'positive' : 1
})

print(train_df[['sentiment' , 'label']].head())

In [32]:
print(train_df[['sentiment' , 'label']].head())
# so this helps to compare with true label using BCEWithLogistLoss

      sentiment  label
47808  positive      1
20154  negative      0
43069  negative      0
19413  negative      0
13673  negative      0

In [33]:
#creating dataset 
from torch.utils.data import Dataset
class IMBDataset(Dataset):
    def __init__(self , dataframe):
        self.reviews = dataframe['clean_review'].tolist()
        self.labels = dataframe['label'].tolist()
    def __len__(self):
        return len(self.reviews)

    def __getitem__(self , index):
        review = encode_and_pad(self.reviews[index])
        label = self.labels[index]

        return torch.tensor(review , dtype = torch.long) , torch.tensor(label , dtype = torch.float32)

In [34]:
#creating train and test datasets 

train_dataset = IMBDataset(train_df)
test_dataset = IMBDataset(test_df)

In [35]:
import torch
x , y = train_dataset[0]
print(x.shape)
print(y)
print(x[:20])

torch.Size([500])
tensor(1.)
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  1,  2, 14, 15, 16, 17,
        18, 19])

In [36]:
#dataloader 

#becuase here every review is a one datset but pytorch trains in batches so we dataloader 
# dataset - dataloader [32 , 500] batch of 32 reviews

In [37]:
from torch.utils.data import DataLoader 
train_loader = DataLoader(
    train_dataset , 
    batch_size = 32, 
    shuffle = True
)

test_loader = DataLoader(
    test_dataset , 
    batch_size = 32 , 
    shuffle = False
)

In [38]:
x_batch , y_batch = next(iter(train_loader)) 
#iter creates an iterator - that gives you next item 
#next gets the next item from it 
print(x_batch.shape)
print(y_batch.shape)
print(x_batch[0])
print(y_batch[0])

#one batch looks like this 

# X = [32, 500]
# Y = [32]

torch.Size([32, 500])
torch.Size([32])
tensor([  428,   708,    21,   313,    70,     2,    79,   364, 28444,    29,
         3079,   887,  4715,   928,    64,   167,    29,    64,  1238,   442,
         3930, 22463,    62,  1391,    29,    62,  2572,    16,   115,   167,
           26,   555,   238,    19,   192,   736,   832,   635,    64,   858,
          141,    13,   832,    64, 12537,  4916,   157,    79,    16,   896,
        29290,    36,     1,  4821,    29,  2716, 20959, 15032,    64, 22289,
           16,   927,     1,  2668,   280,    19,  5425,    70,    64,   167,
          103,    26, 20276,    36,    26, 26409,    26,   735,    11,     4,
          115,   167,    26,   555,   238,   364,  2231,    46,    72,   190,
          209,   851,    16,   252,   191,   606,    29, 43407,    97,   359,
           16,  6715, 10455,   105,   362,   874,   452,   184,   115,  6091,
           11,    72,   548,   362,    26, 26145, 11881,    13,    26,  2679,
         2674,   200, 22666,    29,  6171,    48,    62, 48471,   118,   957,
          876,   167,    55,    64,  2322,    62, 19795,     1,    19,  5057,
           26, 13574,  1680,    62,  6170,    11,    26,     1,    26,   222,
          167,     1,  1394,   362,    91,    72,    43,  1541,     8,    26,
            1,    46,    26, 14220, 14221,   457,    15,    26,   882,   776,
          560,  5905,   158,     4,  1530,    36,   765,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor(1.)

In [39]:
#we can also manually move throuugh batches 
loader_iterator = iter(train_loader)
batch1 = next(loader_iterator)
batch2 = next(loader_iterator)
print(batch1[0].shape)
print(batch1[0].shape)

torch.Size([32, 500])
torch.Size([32, 500])

In [40]:
#embedding = [32 , 500 , 64 ] 
#we dont want the padding to get the embedding and get a value for that 
#so we deal with maskig - mean pooling - linear - bcewithlogistloss

In [41]:
#creating embedding 
import torch.nn as nn
embedding = nn.Embedding(
    num_embeddings = len(vocab),
    embedding_dim = 64,
    padding_idx = 0
)
embedded = embedding(x_batch)
print(x_batch.shape)
print(embedded.shape)

torch.Size([32, 500])
torch.Size([32, 500, 64])

In [42]:
# #mean pooling x.mean(dim = 1) dim=0 - reviews , dim=1 - tokens dim=2 embedding values 
# #hence we are supposed to average across the 500 tokens 
# # review_vector = embedded.mean(dim = 1)

# #rather than using if we use mask 
# embedding = 32 , 500 , 64 
# masking tells us what is true and padded vectors 
# example in a review 5 words are real remaining 495 are 0 padded then each 64 - dim = [64]...5 times 5*64 
# we want 1 * 64 we have different methods one is max pooling

In [43]:
# review_vector = embedded.mean(dim = 1)
# mask = (x_batch != 0)
mask = (x_batch != 0).unsqueeze(-1)
embedded = embedded * mask  #this will give 0 for padded and 1 for real vector it keeps it 
#calxulate the sum of real tokens 
sum_embeddings = embedded.sum(dim = 1)
#divide by real tokens 
num_tokens = mask.sum(dim = 1)
review_vector = sum_embeddings / num_tokens.clamp(min = 1)
#averaging only the real tokens hence 500 to ignoring padding - averaging real tokens - one 64 dimensional vector 
# [32 , 500 , 64] - masked mean pooling - [32 , 64]

Vector                 Mask       Result

[0.2, 0.5, -0.1]   ×   True   → [0.2, 0.5, -0.1]
[0.7, 0.1,  0.3]   ×   False  → [0.0, 0.0,  0.0]
This is also called masking by multiplication.

In [44]:
# #building the actual model 
# input = [32 , 500] 
# embedding - [32 , 500 , 64]
# masked mean pooling [32 , 64]
# linear = 32 ,1 
# logit

In [45]:
#step 1 
import torch 
import torch.nn as nn
class SentimentalModel(nn.Module):
    def __init__(self , vocab_size , embedding_dim):
        super().__init__()
        self.embedding = nn.Embedding(
            num_embeddings = vocab_size,
            embedding_dim = embedding_dim ,
            padding_idx = 0
        ) 
        self.linear = nn.Linear(embedding_dim,1)
    def forward(self , x):
         embedded = self.embedding(x) #batch , 500
         mask = (x!= 0).unsqueeze(-1) #batch , 500 , 1
         embedded = embedded * mask #remove the pad Vectors
         sum_embeddings = embedded.sum(dim =1 ) #batch , 64

         num_tokens = mask.sum(dim =1) #number of real tokens 
         review_vector =(                                 #[batch , 64]
                sum_embeddings / num_tokens.clamp(min = 1)
                
            )
            #[batch , 1]

         logits = self.linear(review_vector)
         return logits

In [46]:
#creatng a model 
#len(vocab) = 59847
#embedding_dim = 64 

model = SentimentalModel(vocab_size = len(vocab),
                        embedding_dim = 64)

In [47]:
# $testing it 
logits = model(x_batch)
print(logits.shape)

torch.Size([32, 1])

In [48]:
#the embedding and linear layer contain only randomly paramaterized 
#now we are supposed to train it 
#1 . LOSS function - binary classification - 0 , 1: BCEWithLogistsLOss
criterion = nn.BCEWithLogitsLoss()
logits = model(x_batch)
loss = criterion(
    logits.squeeze(1) , #squeeze(1) - we want 32 because y label = 32 
    y_batch
)
print(loss)

tensor(0.6874, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [49]:
#with training 
optimizer = torch.optim.Adam(
    model.parameters() , # now our model has learnable parameters 
    lr = 0.001
)

In [50]:
#training step 
optimizer.zero_grad()
logits = model(x_batch)
loss = criterion(logits.squeeze(1),
                y_batch)
loss.backward()
optimizer.step()
print(loss.item())

0.6874376535415649

In [51]:
# model.train() 
# #doesn't train the model by itself but tells put this model into training mode 
# total_loss = 0


# for x_batch , y_batch in train_loader:
#     optimizer.zero_grad()
#     logits = model(x_batch)
#     loss = criterion(
#         logits.squeeze(1) , 
#         y_batch
#     )
#     loss.backward()
#     optimizer.step()
#     total_loss += loss.item() 
#     #total_loss = loss from batch1 + loss from batch2 + loss from batch3 ....1250 batches
#     # later after 1250 we calculate the average loss average loss = total loss/len(train_loader) train_loader is the number of batches  
# #item() extracts the number 
# #we calculate the loss for every epoch

40k training reviews (datset) = 32 batch size 
splited - batch 1 ---batch2---batch3 ----batch1250  40k/32 = 1250 batches

In [52]:
num_epochs = 3 
for epoch in range(num_epochs):
    model.train()

    total_loss = 0       # reset for this epoch

    for x_batch, y_batch in train_loader:

        optimizer.zero_grad()

        logits = model(x_batch)
#we pass the raw scores into loss not probabilities loogit are raw scores 
        loss = criterion(
            logits.squeeze(1),
            y_batch
        )  

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    average_loss = total_loss / len(train_loader)

    print(f"Epoch {epoch + 1}:Loss = {average_loss:4f}")

Epoch 1:Loss = 0.565934
Epoch 2:Loss = 0.332539
Epoch 3:Loss = 0.248312

In [53]:
#model weights doesnt resets but loss resets at each epoch 
#loss can fluctuates between the epochs 
#gradient tells which direction increases the loss 
#example : if i increase this wieght , what happens to the loss ?

model.train() - puts the model into training mode - this matters for dropout and batch normalization becuase they behave differentky during training and evaluation 
model.eval() - with torch.no_grad(): 
logits = model(X) 
midel.eval switches the layers droput and batch normalization as these behave differently during evaluation and training 'torch.no_grad() - stops pytorch calculating gradient
model(x) - nakes the predecition using the current wieghts 
loss_fn(logits , y) - measures prediction error 
logits = model(x) - stores the raw prediction scores . for binary classification we cant convert tp probability by using sigmoid (torch.sigmoid(logits))

In [54]:
#evaluation mode 
model.eval()
with torch.no_grad():
    x_batch , y_batch = next(iter(test_loader))
    logits = model(x_batch).squeeze(1)
    probabilities = torch.sigmoid(logits)
    predictions = (probabilities >= 0.5).float()
print("actual labels :" , y_batch[:10])
print("probabilities:" , probabilities[:10])
print("predictions: " , predictions[:10])

actual labels : tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])
probabilities: tensor([0.1725, 0.9381, 0.7294, 0.0585, 0.0375, 0.0115, 0.0546, 0.1612, 0.4425,
        0.0956])
predictions:  tensor([0., 1., 1., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
#to  
model.eval()
correct = 0
total = 0
all_predictions = []
all_labels = []
with torch.no_grad():
    for x_batch , y_batch in test_loader:
        logits = model(x_batch).squeeze(1)
        probabilities = torch.sigmoid(logits)
        predictions = (probabilities >= 0.5).float()
        correct += (predictions == y_batch).sum().item()
        total += y_batch.size(0)
        all_predictions.extend(predictions.cpu().numpy())
        all_labels.extend(y_batch.cpu().numpy())
accuracy = correct / total 
print(f"correct predcitions:{correct}/{total}")
print(f"test accuracy:{accuracy * 100:.2f}%")
#accuary is overall score not h=just about posistie 
# 45 + 44 = 89
#89 / 100 * 100 = 89 %

correct predcitions:8915/10000
test accuracy:89.15%

In [56]:
# confusion matrix- tells us which precitions are correct and which are wrong
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(all_labels , all_predictions)
print(cm)

[[4451  549]
 [ 536 4464]]

In [57]:
# preciosn  - of all the reviews model predicted as positive , how many were actually positive 
# precision = tp/tp+fp
# recall = true positive / true positive + false negative hence more false negatives more recalll is decreases 

#f1 score = combining precision + recall gives high score when r and p are high low when they are low 


#f1 = 2 * (p * r)/ (p + r)

from sklearn.metrics import f1_score 
f1 = f1_score(all_labels , all_predictions)
print(f"f1 score : {f1:.4f} ")
print(f"f1 score:{f1 * 100:.2f}%")

f1 score : 0.8916
f1 score:89.16%

In [58]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

print("Accuracy:", accuracy_score(all_labels, all_predictions))
print("Precision:", precision_score(all_labels, all_predictions))
print("Recall:", recall_score(all_labels, all_predictions))
print("F1-score:", f1_score(all_labels, all_predictions))

print(classification_report(
    all_labels,
    all_predictions,
    target_names=["Negative", "Positive"]
))

Accuracy: 0.8915
Precision: 0.8904847396768402
Recall: 0.8928
F1-score: 0.891640866873065
              precision    recall  f1-score   support

    Negative       0.89      0.89      0.89      5000
    Positive       0.89      0.89      0.89      5000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

from sklearn.metrics import classification_report
print(classification_report(
all_labels,
all_predictions,
target_names = ['Negative' ,'Positive']))

In [60]:
from sklearn.metrics import classification_report
print(classification_report(
all_labels,
all_predictions,
target_names = ['Negative' ,'Positive']))

              precision    recall  f1-score   support

    Negative       0.89      0.89      0.89      5000
    Positive       0.89      0.89      0.89      5000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

In [61]:
import torch
import json

# Save the trained model
torch.save(
    model.state_dict(),
    "/kaggle/working/sentiment_model.pth"
)

# Save the vocabulary
with open("/kaggle/working/vocab.json", "w", encoding="utf-8") as f:
    json.dump(vocab, f)

print("Model and vocabulary saved successfully!")

Model and vocabulary saved successfully!

In [62]:
import json

config = {
    "embedding_dim": 64,
    "max_len": 500,
    "vocab_size": len(vocab),
    "pad_id": 0,
    "unk_id": 1,
    "threshold": 0.5,
    "min_freq": 5
}

with open("/kaggle/working/config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=4)

print("Configuration saved:", config)

Configuration saved: {'embedding_dim': 64, 'max_len': 500, 'vocab_size': 59847, 'pad_id': 0, 'unk_id': 1, 'threshold': 0.5, 'min_freq': 5}

In [63]:
import os

for filename in [
    "sentiment_model.pth",
    "vocab.json",
    "config.json"
]:
    path = f"/kaggle/working/{filename}"
    print(filename, "—", "Found ✅" if os.path.exists(path) else "Missing ❌")

sentiment_model.pth — Found ✅
vocab.json — Found ✅
config.json — Found ✅